Dockerfile and attendant setup files
Ensembl/ensembl-prodinf-metadata pull request #3
Opened 2021-04-30 10:27 UTC by james-monkeyshines

2021-04-30 13:25 UTC, marcoooo commented
@vinay-ebi I am not the best for Docker things, so I added you as a reviewer, Thanks!

2021-04-30 13:32 UTC, marcoooo requested changes

2021-04-30 13:32 UTC, marcoooo commented on setup.py
> +from pathlib import Path
License to add

2021-04-30 14:12 UTC, vinay-ebi approved these changes
For reference:  Its good to create non root user for docker container to avoid break out in unusual conditions

2021-05-04 07:19 UTC, marcoooo approved these changes

2021-05-04 07:29 UTC, merged